### ISSUE TITLE
It would be nice if SrtSocket conformed to io.Writer

### ISSUE THREAD

**Issue by eric** [Haivision/srtgo#11]
The `Write()` function takes an extra `timeout int` argument that makes it so that it doesn't conform to `io.Writer`. It would be nice if we adjusted the API so that there was a default timeout for a given instance and then a separate `WriteWithTimeout()` function that took a timeout that overrode the default.

**Comment by jurisbu** [comment]
This is really a missed opportunity.  For now I have to wrap SrtSocket and override Read() and Write().

```go
type WrappedSrtSocket struct {
	*srtgo.SrtSocket
	timeout int
}

func NewWrappedSrtSocket(s *srtgo.SrtSocket, timeout int) *WrappedSrtSocket {
	return &WrappedSrtSocket{s, timeout}
}

func (s *WrappedSrtSocket) Read(b []byte) (int, error) {
	return s.SrtSocket.Read(b, s.timeout)
}

func (s *WrappedSrtSocket) Write(b []byte) (int, error) {
	return s.SrtSocket.Write(b, s.timeout)
}
```

With this in place one can simply use sat `io.Copy` to pass data between say 2 SRT connections:

```go
// ...
inSrt := NewWrappedSrtSocket(s1, 0)
outSrt := NewWrappedSrtSocket(s2, 0)

n, err := io.Copy(outSrt, inSrt)
// ...
```

**Comment by jeoliva** [comment]
Although applying this change (removing timeout parameter from Read/Write operations) will break backward-compatibility, which I don't like at all, I think the benefits we will get are bigger than the problems caused (or the time it will take to fix those compatibility issues). 

I will apply the requested change. Hope this doesn't cause big problems to you.

**Comment by jeoliva** [comment]
Fixed in https://github.com/Haivision/srtgo/commit/513b375af39c739a951edd66bf71fb0744ca4557.

Please, note this breaks backward-compatibility.

**Comment by eric** [comment]
I feel like it would still be nice to have a version of `Read` and `Write` that does take a timeout (like `WriteWithTimeout()`) to accommodate other sorts of situations.
