### ISSUE TITLE
Test data  video feeds

### ISSUE THREAD

**Issue by gedw99** [Haivision/srtgo#16]
Are there any test data files of SRT sources that represent the different set versions.

To help debug and regression test a set project I am working on.

if you have a suggestion of other approaches to devE/E testing a regression testing please chime in

**Comment by jeoliva** [comment]
I don't think there is such thing. What I typically do is generating synthetic content streams using ffmpeg so I can play with different scenarios but, unfortunately, that is not useful to cover your case (testing with different versions).
