### ISSUE TITLE
cannot use timeoutMs (type _Ctype_longlong) as type _Ctype_long

### ISSUE THREAD

**Issue by cchanms** [Haivision/srtgo#3]
Hi, I'm getting this error:

```
# github.com/haivision/srtgo
/go/src/github.com/haivision/srtgo/srtgo.go:174:60: cannot use timeoutMs (type _Ctype_longlong) as type _Ctype_long in argument to _Cfunc_srt_epoll_wait
/go/src/github.com/haivision/srtgo/srtgo.go:214:60: cannot use timeoutMs (type _Ctype_longlong) as type _Ctype_long in argument to _Cfunc_srt_epoll_wait
/go/src/github.com/haivision/srtgo/srtgo.go:239:45: cannot use timeoutMs (type _Ctype_longlong) as type _Ctype_long in argument to _Cfunc_srt_epoll_wait
/go/src/github.com/haivision/srtgo/srtgo.go:264:64: cannot use timeoutMs (type _Ctype_longlong) as type _Ctype_long in argument to _Cfunc_srt_epoll_wait
```

Using SRT version: 1.4.1 and golang version: 1.13.8

**Comment by cdavid14** [comment]
Same here with SRT commit e6f2c62 and golang version 1.14.3 , this comes with commit f1415a3 ; @epiclabsDASH can you confirm what SRT and golang version are you using to test the library?

**Comment by krabiswabbie** [comment]
I agree, just faced with the same issue trying to install srtgo.
go version go1.14 linux/amd64, commit f1415a3

**Comment by jeoliva** [comment]
I am using:
- srt 1.4.1
- go version go1.14.3 darwin/amd64
- MacOS Catalina

And it does not work when using C.long(-1). I am taking a look to see what is the right way to keep this "cross compatible".

**Comment by jeoliva** [comment]
Seems like the definition of uint64_t in linux
`typedef unsigned long int __uint64_t;`

is different than its definition in MacOS:
`typedef unsigned long long uint64_t;`

**Comment by krabiswabbie** [comment]
Yes, this is a known case about Linux/Macos, check for example https://stackoverflow.com/questions/36814040/osx-vs-linux-how-to-deal-with-unsigned-long-and-uint64-t

Obviously, try to use C.int64_t in your case (signed).

**Comment by jeoliva** [comment]
Thanks! Fixed
